### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by olleharstedt** [colder/phantm#12]
I'm working on a similar project myself, but simpler. Just wanted to know what's up with this one.

Regards
Olle

**Comment by colder** [comment]
The project is not abandoned per-se, but it supports only up to 5.3 which is now EOL.

I had a plan to use a different parser generator, allowing Phantm to support more recent PHP version, but it fell short.

In summary, it is not formally abandoned but quite outdated and I don't have the time (at least now) to work on it.

**Comment by olleharstedt** [comment]
Ah, OK, thanks for the info.
