### ISSUE TITLE
Support for namespaces

### ISSUE THREAD

**Issue by samo9789** [colder/phantm#5]
Hi,

I have tried to use phantm to validate my source code and, unless I missed something, namespaces in PHP are not supported by phantm. Will you add support for this anytime soon ?

Thank you

**Comment by colder** [comment]
Hi,

I currently have very little time to work on phantm. Rest assured though, despite the lack of activity on it for several months, I still plan to work on it and update it to 5.4/5.5.

Given the nature of the namespaces implementation in PHP, they would be relatively trivial to implement in phantm.

Best Regards,

**Comment by samo9789** [comment]
Hi,

Great news ! I will stay tuned. 

Samantha

**Comment by jthomaskerr** [comment]
I'm interested in implementing namespaces for you. Can you give me a few quick suggestions about how to go about it?

Joe.

**Comment by colder** [comment]
Hi, 

namespaces in PHP are simply class renamings. So basically I would implement namespaces in phantm while parsing, by keeping a set of renaming rules and applying them on found class names.

In the end it should be pretty straightforward.

Best,

**Comment by colder** [comment]
Namespaces should now be implemented in master.

Best

**Comment by samo9789** [comment]
Hi,

Thanks a lot for implementing the namespaces. I am just now getting back to this and trying to run this on some files of my projects. 

I still have two questions for you, if you don't mind  checking this out. 

1) I have a problem with the inclusion of use statements. 

2) I have a problem launching the check 

Thanks a lot for your help 

1)

I have a PostController.php file in application/controllers/api/v3
and I have an ApiBaseController.php file in the same folder. 
PostController.php starts with : 
use application\controllers\api\v3;
class PostController extends ApiBaseController

I run phantm with include path : 

java -jar target/phantm-assembly-1.0.7.jar --includepath ".:/path/to/application" /path/to/application/controllers/api/v3/PostController.php

It always says : 

Error: Class application\controllers\api\v3\PostController extends non-existent class application\controllers\api\v3\ApiBaseController

It fails to find the file referenced in the use. What am I not declaring right ? 

2) 

After installing, I get the following two calls to work 

java -jar target/phantm-assembly-1.0.7.jar /Users/samobk/Workspace/bktrunk/application/controllers/api/v3/PostController.php

RUNS

and 

/usr/local/bin/sbt "run /Users/samobk/Workspace/bktrunk/application/controllers/api/v3/PostController.php"

though

./phantm /Users/samobk/Workspace/bktrunk/application/controllers/api/v3/PostController.php

FALIS

```
    ____  __                __
   / __ \/ /_  ____  ____  / /_____ ___
```

   -- / /_/ / __ \/ __ `/ __ \/ __/ __`__ \  --
  -- / ____/ / / / /_/ / / / / /_/ / / / / / --
 -- /_/   /_/ /_/__,_/_/ /_/__/_/ /_/ /_/ --

Exception in thread "main" java.lang.RuntimeException: Cannot figure out how to run target: phantm.Main
    at scala.sys.package$.error(package.scala:27)
    at scala.tools.nsc.GenericRunnerCommand.scala$tools$nsc$GenericRunnerCommand$$guessHowToRun(GenericRunnerCommand.scala:38)
    at scala.tools.nsc.GenericRunnerCommand$$anonfun$2.apply(GenericRunnerCommand.scala:48)
    at scala.tools.nsc.GenericRunnerCommand$$anonfun$2.apply(GenericRunnerCommand.scala:48)
    at scala.Option.getOrElse(Option.scala:108)
    at scala.tools.nsc.GenericRunnerCommand.<init>(GenericRunnerCommand.scala:48)
    at scala.tools.nsc.GenericRunnerCommand.<init>(GenericRunnerCommand.scala:17)
    at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:33)
    at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:89)
    at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)

Do you have any sea what I am missing ?

**Comment by colder** [comment]
Hi,

1)
did you include the file declaring ApiBaseController.php properly? Or are you relying on an autoloader?

2)
./phantm is a script htat I was using locally, it might very well be that it is not adapted to your environment. I will have to check.

**Comment by samo9789** [comment]
1) it's loaded with the include_path

**Comment by colder** [comment]
ok, but the include_path setting is equivalent to the one of PHP, it does not auto-include files, it specifies where to look when you do include 'foo.php'
see http://php.net/include_path

**Comment by samo9789** [comment]
There are no require_once of the files, just the use statement. 

If I add a require_once of ApiBaseController, it loads that just fine but fails on another higher level class which is also loaded with an use statement.

**Comment by colder** [comment]
I think there is some miscommunication: without any require, the code you have will not run in PHP, unless you have an autoloader that will include missing classes.

The "use" statement certainly won't "load" classes or include files. it will simply specify how to resolve class identifiers found in your code.

Do you maybe have a reproducible, self-contained example illustrating your issue ?

Best,

**Comment by samo9789** [comment]
I'm sorry, yes, there is an autoload  defined in the framework : 

is there a way to "declare" it in phntm ? 

Samantha

**Comment by colder** [comment]
Hi,

As far as I can tell no, it is not supported. This is a hard feature to support as it requires executing PHP code. It might be doable by evaluating the autoloader, if simple enough, but this is not yet supported.

For now, if you want to run phantm on a project, you should explicitely include every classes to make sure that the autoloader is not required.
